import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { Toaster } from "@/components/ui";
import { SideNavigation } from "@/components/common";
import "@/styles/globals.css";
import "@/styles/main.scss";

const NOTO_SANS_KR = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TODO Task Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={NOTO_SANS_KR.className}>
        <div className="page">
          <SideNavigation />
          <div className="page__main">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
